# Generated by Django 4.2.7 on 2023-11-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_profileuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Характер  отказа')),
            ],
        ),
        migrations.CreateModel(
            name='PartSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='способ восстановления')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRefusal', models.DateField(db_index=True, verbose_name='Дата отказа')),
                ('operatingTime', models.CharField(blank=True, max_length=128, verbose_name='Наработка')),
                ('descriptionFailure', models.TextField(verbose_name='Описание отказа')),
                ('partSpare', models.TextField(verbose_name='Используемые запасные части')),
                ('dataRecovery', models.DateField(blank=True, db_index=True, verbose_name='Дата восстановления')),
                ('downtime', models.CharField(blank=True, max_length=128, verbose_name='Время простоя')),
                ('componyServisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.serviscompanies', verbose_name='Сервисная компания')),
                ('metodRecovery', models.ForeignKey(blank=True, max_length=128, on_delete=django.db.models.deletion.PROTECT, to='complaints.partspare', verbose_name='Способ восстановления')),
                ('nodeFailure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.nodefailure', verbose_name='Узел отказа')),
            ],
            options={
                'verbose_name': 'Рекламации',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
