# Generated by Django 4.2.7 on 2023-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefailure',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Характер  отказа'),
        ),
        migrations.AlterField(
            model_name='partspare',
            name='name',
            field=models.CharField(max_length=128, verbose_name='способ восстановления'),
        ),
    ]
